# Generated by Django 5.2 on 2025-04-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='JackpotSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='JackpotSetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('jackpot_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jackpot_set.jackpotset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('jackpot_set', 'product')},
            },
        ),
        migrations.AddField(
            model_name='jackpotset',
            name='products',
            field=models.ManyToManyField(related_name='jackpot_sets', through='jackpot_set.JackpotSetProduct', to='products.product'),
        ),
    ]
