# Generated by Django 5.2 on 2025-04-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot_set', '0003_rename_product_jackpotsetproduct_gift_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jackpotset',
            old_name='products',
            new_name='gifts',
        ),
    ]
