# Generated by Django 5.2 on 2025-04-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qtn',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
