# Generated by Django 4.2.14 on 2025-04-17 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_variant_chance_of_winning_variant_countdown_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='chance_of_winning',
            field=models.IntegerField(choices=[(1, '1 - Very Hard'), (2, '2 - Hard'), (3, '3 - Medium'), (4, '4 - Easy'), (5, '5 - Very Easy')], default=3, help_text='This field defines the probability of winning in the game page. 1 is the hardest and 5 is the easiest.', verbose_name='Chance of Winning'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='countdown_minutes',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Countdown (minutes)'),
        ),
    ]
