# Generated by Django 4.2.14 on 2025-04-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_alter_variant_chance_of_winning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='copy_full_title',
            field=models.CharField(default='🎰 Spin to Win Big! 🎰', max_length=255, verbose_name='Copy full title'),
        ),
        migrations.AddField(
            model_name='variant',
            name='copy_title_highlight',
            field=models.CharField(default='Win Big!', max_length=255, verbose_name='Copy title highlight'),
        ),
    ]
