# Generated by Django 4.2.14 on 2025-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0004_variant_copy_full_title_variant_copy_title_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='gifts_full_title',
            field=models.CharField(default='Gifts You Might Win', max_length=255, verbose_name='Gifts section full title'),
        ),
        migrations.AddField(
            model_name='variant',
            name='gifts_title_highlight',
            field=models.CharField(default='Might Win', max_length=255, verbose_name='Gifts section title highlight'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='copy_full_title',
            field=models.CharField(default='🎰 Spin to Win Big! 🎰', max_length=255, verbose_name='Copy section full title'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='copy_title_highlight',
            field=models.CharField(default='Win Big!', max_length=255, verbose_name='Copy section title highlight'),
        ),
    ]
