# Generated by Django 4.2.14 on 2025-04-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0005_variant_gifts_full_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='jackpot_full_title',
            field=models.CharField(default='Spin & Win Awesome Prizes', max_length=255, verbose_name='Jackpot section full title'),
        ),
        migrations.AddField(
            model_name='variant',
            name='jackpot_title_highlight',
            field=models.CharField(default='Win Awesome Prizes', max_length=255, verbose_name='Jackpot section title highlight'),
        ),
    ]
