# Generated by Django 4.2.14 on 2025-04-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0006_variant_jackpot_full_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='products_table_full_title',
            field=models.CharField(default='Check Out Your Musical Picks', max_length=255, verbose_name='Product table full title'),
        ),
        migrations.AddField(
            model_name='variant',
            name='products_table_title_highlight',
            field=models.CharField(default='Musical Picks', max_length=255, verbose_name='Product table title highlight'),
        ),
    ]
