# Generated by Django 5.2 on 2025-04-17 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackpot_set', '0002_remove_jackpotsetproduct_quantity'),
        ('variants', '0007_variant_products_table_full_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='jackpot_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jackpot_set.jackpotset'),
        ),
    ]
