# Generated by Django 5.2 on 2025-04-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount'),
        ('variants', '0008_variant_jackpot_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='products',
            field=models.ManyToManyField(related_name='variants', to='products.product'),
        ),
    ]
