# Generated by Django 5.2 on 2025-04-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount'),
        ('variants', '0009_variant_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='products',
            field=models.ManyToManyField(help_text='Products to be shown on page cart.', related_name='variants', to='products.product'),
        ),
    ]
