# Generated by Django 5.2 on 2025-04-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0010_variant_active_alter_variant_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='chance_of_winning',
            new_name='chances_of_winning',
        ),
    ]
