# Generated by Django 5.2 on 2025-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0011_rename_chance_of_winning_variant_chances_of_winning'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='copy_text',
            field=models.TextField(blank=True, null=True, verbose_name='Copy Text'),
        ),
    ]
