import { ProductsProvider } from '@/hooks/useProducts'
import { ThemesProvider } from '@/hooks/useTheme'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import '../styles/index.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Home | Start Next App',
    template: '%s | Start Next App'
  },
  description: 'Generated by test Start Next App'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${inter.className} h-full scroll-smooth bg-white antialiased`}>
      <body className="bg-light text-dark" suppressHydrationWarning>
        <ThemesProvider>
          <ProductsProvider>
            <div
              id="app"
            >
              {children}
            </div>
          </ProductsProvider>
        </ThemesProvider>
      </body>
    </html>
  )
}
